name: Build and Push

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build Marauder Binaries
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Install ESP32 Boards and Compile TestFile
        uses: ArminJo/arduino-test-compile@v3.2.1
        with:
          sketch-names: TestFile.ino
          arduino-board-fqbn: esp32:esp32:esp32s2
          platform-url: https://github.com/espressif/arduino-esp32/releases/download/2.0.10/package_esp32_dev_index.json
        
      - name: Pull arduino-esp32 v2.0.4
        uses: actions/checkout@v2
        with:
          repository: espressif/arduino-esp32
          ref: 2.0.4
          path: 2.0.4arduino-esp32
          
      - name: Pull arduino-esp32 v2.0.10
        uses: actions/checkout@v2
        with:
          repository: espressif/arduino-esp32
          ref: 2.0.10
          path: 2.0.10
          
      - name: Install AsyncTCP
        uses: actions/checkout@v2
        with:
          repository: me-no-dev/AsyncTCP
          ref: master
          path: CustomAsyncTCP
          
      - name: Install MicroNMEA
        uses: actions/checkout@v2
        with:
          repository: stevemarple/MicroNMEA
          ref: v2.0.6
          path: CustomMicroNMEA
          
      - name: Install ESPAsyncWebServer
        uses: actions/checkout@v2
        with:
          repository: bigbrodude6119/ESPAsyncWebServer
          ref: master
          path: CustomESPAsyncWebServer

      #- name: Install TFT_eSPI
      #  uses: actions/checkout@v2
      #  with:
      #    repository: justcallmekoko/TFT_eSPI
      #    ref: master
      #    path: CustomTFT_eSPI
          
      - name: Install TFT_eSPI
        uses: actions/checkout@v2
        with:
          repository: Bodmer/TFT_eSPI
          ref: 2.2.23
          path: CustomTFT_eSPI

      - name: Install lv_arduino
        uses: actions/checkout@v2
        with:
          repository: lvgl/lv_arduino
          ref: 3.0.0
          path: Customlv_arduino

      - name: Install JPEGDecoder
        uses: actions/checkout@v2
        with:
          repository: Bodmer/JPEGDecoder
          ref: 1.8.0
          path: CustomJPEGDecoder

      - name: Install NimBLE-Arduino
        uses: actions/checkout@v2
        with:
          repository: h2zero/NimBLE-Arduino
          ref: 1.2.0
          path: CustomNimBLE-Arduino

      - name: Install Adafruit_NeoPixel
        uses: actions/checkout@v2
        with:
          repository: adafruit/Adafruit_NeoPixel
          ref: 1.10.7
          path: CustomAdafruit_NeoPixel

      - name: Install ArduinoJson
        uses: actions/checkout@v2
        with:
          repository: bblanchon/ArduinoJson
          ref: v6.18.2
          path: CustomArduinoJson

      - name: Install SwitchLib
        uses: actions/checkout@v2
        with:
          repository: justcallmekoko/SwitchLib
          ref: main
          path: CustomSwitchLib
          
      - name: Install LinkedList
        uses: actions/checkout@v2
        with:
          repository: ivanseidel/LinkedList
          ref: v1.3.3
          path: CustomLinkedList
          
      - name: Install EspSoftwareSerial
        uses: actions/checkout@v2
        with:
          repository: plerup/espsoftwareserial
          ref: 8.1.0
          path: CustomEspSoftwareSerial
          
      #- name: Search for SD lib in arduino-esp32 v2.0.4
      #  run: |
      #    find /home/runner/work/ESP32Marauder/ESP32Marauder/2.0.4arduino-esp32 -name "SD"
          
      - name: Configure TFT_eSPI
        run: |
          rm -f CustomTFT_eSPI/User_Setup_Select.h
          cp User_Setup_Select.h CustomTFT_eSPI/
          cp User_Setup_marauder_mini.h CustomTFT_eSPI/
          cp User_Setup_og_marauder.h CustomTFT_eSPI/
          cp User_Setup_marauder_m5stickc.h CustomTFT_eSPI/
          pwd
          ls -la
          ls -la CustomTFT_eSPI
          
      #- name: Place 2.0.10 for use
      #  run: |
      #    mkdir -p /home/runner/.arduino15/packages/esp32/hardware/esp32/
      #    cp -R /home/runner/work/ESP32Marauder/ESP32Marauder/2.0.3 /home/runner/.arduino15/packages/esp32/hardware/esp32/2.0.3
      #    ls -la /home/runner/.arduino15/packages/esp32/hardware/esp32/
      #    echo Whoever made me have to do this can fuck off
          
      #- name: Replace arduino-esp32 v2.0.10 that was gloriously forced on us
      #  run: |
      #    rm -rf /home/runner/.arduino15/packages/esp32/hardware/esp32/2.0.10
      #    cp -R /home/runner/work/ESP32Marauder/ESP32Marauder/2.0.3 /home/runner/.arduino15/packages/esp32/hardware/esp32/2.0.3
      #    ls -la /home/runner/.arduino15/packages/esp32/hardware/esp32/
      #    echo Whoever made me have to do this can fuck off
          
      #- name: Search for SD lib in arduino-esp32
      #  run: |
      #    find /home/runner/ -name "SD"
          
      #- name: Replace SD lib
      #  run: |
      #    rm -rf /home/runner/.arduino15/packages/esp32/hardware/esp32/2.0.10/libraries/SD
      #    cp -R /home/runner/work/ESP32Marauder/ESP32Marauder/2.0.4arduino-esp32/libraries/SD /home/runner/.arduino15/packages/esp32/hardware/esp32/2.0.10/libraries/SD
      #    ls -la /home/runner/.arduino15/packages/esp32/hardware/esp32/2.0.10/libraries/SD
          
      - name: Modify platform.txt
        run: |
          echo "Chicken"
          for i in $(find /home/runner/.arduino15/packages/esp32/hardware/esp32/ -name "platform.txt"); do
            sed -i 's/compiler.c.elf.libs.esp32c3=/compiler.c.elf.libs.esp32c3=-zmuldefs /' "$i"
            sed -i 's/compiler.c.elf.libs.esp32s3=/compiler.c.elf.libs.esp32s3=-zmuldefs /' "$i"
            sed -i 's/compiler.c.elf.libs.esp32s2=/compiler.c.elf.libs.esp32s2=-zmuldefs /' "$i"
            sed -i 's/compiler.c.elf.libs.esp32=/compiler.c.elf.libs.esp32=-zmuldefs /' "$i"
            cat "$i" | grep compiler.c.elf.libs.esp32c3
            cat "$i" | grep compiler.c.elf.libs.esp32s3
            cat "$i" | grep compiler.c.elf.libs.esp32s2
            cat "$i" | grep compiler.c.elf.libs.esp32
          done
          

      - name: Build Marauder for AtomS3 Board
        uses: ArminJo/arduino-test-compile@v3.2.1
        with:
          sketch-names: esp32_marauder.ino
          arduino-board-fqbn: esp32:esp32:esp32s3:PartitionScheme=min_spiffs,FlashSize=8M,PSRAM=enabled
          extra-arduino-cli-args: "--warnings none"
          
      - name: Rename Marauder AtomS3 bin
        run: |
          mv ./esp32_marauder/build/esp32.esp32.esp32s3/esp32_marauder.ino.bin ./esp32_marauder/build/esp32.esp32.esp32s3/esp32_marauder.atomS3.bin





      - name: Display finished bins
        run: |
          find ./esp32_marauder/build -name "*.bin"
          
      - name: 'Upload Marauder AtomS3 Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: esp32_marauder.atomS3.bin
          path: ./esp32_marauder/build/esp32.esp32.esp32s3/esp32_marauder.atomS3.bin
          retention-days: 5
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false
        if: github.event_name != 'pull_request'
          
      - name: Upload AtomS3 Asset
        id: upload-atomS3-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./esp32_marauder/build/esp32.esp32.esp32s3/esp32_marauder.atomS3.bin
          asset_name: esp32_marauder.atomS3.bin
          asset_content_type: application/bin
        if: github.event_name != 'pull_request'